"""Problem 2: Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""
def fibonacci_even_numbers(upper_bound):
    total, a, b = 0, 1, 2
    while True:
        if a % 2 == 0:
            total += a
        a, b = b, a + b
        if a > upper_bound:
            break
    return total


if __name__ == '__main__':
    print('Sum of even numbers: {0:,}'.format(fibonacci_even_numbers(4.0E6)))
